fragment PageParts on Page {
  __typename
  heroTagline
  heroTitle
  heroImage
  experienceImage
  experienceTitle
  experienceText
  theme {
    __typename
    primaryColor
    backgroundColor
    heroTitleSize
  }
  offerings {
    __typename
    title
    description
    image
  }
}
